POST {{ baseUrl }}/api/v1/auth/create_admin_account
Content-Type: application/json
{
    "email": "pascalobi83@gmail.com",
    "fullName": "Pascal OBI",
    "password": "StrongP@ssw0rd!",
    "phone": "+2348131234567"
}