POST {{ baseUrl }}/api/v1/auth/create_guardian_account
Content-Type: application/json
{
    "email": "bilmatechnologiesltd@gmail.com",
    "fullName": "Guardian User Test",
    "password": "StrongP@ssw0rd!",
    "phone": "+2348131234567",
    "isTermsAndPrivacyAccepted": true
}